<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./src/lib/Character.glb
-->

<script>
  import { Group } from 'three'
  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/Character.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T is={ref} {...$$restProps}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Root_Scene">
      <T.Group name="RootNode">
        <T.Group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <T is={gltf.nodes.Root} />
        </T.Group>
        <T.Group name="MushroomKing" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <T.SkinnedMesh
            name="MushroomKing_1"
            geometry={gltf.nodes.MushroomKing_1.geometry}
            material={gltf.materials.MushroomKing_Main}
            skeleton={gltf.nodes.MushroomKing_1.skeleton}
          />
          <T.SkinnedMesh
            name="MushroomKing_2"
            geometry={gltf.nodes.MushroomKing_2.geometry}
            material={gltf.materials.Orc_Main}
            skeleton={gltf.nodes.MushroomKing_2.skeleton}
          />
          <T.SkinnedMesh
            name="MushroomKing_3"
            geometry={gltf.nodes.MushroomKing_3.geometry}
            material={gltf.materials.MushroomKing_Secondary}
            skeleton={gltf.nodes.MushroomKing_3.skeleton}
          />
          <T.SkinnedMesh
            name="MushroomKing_4"
            geometry={gltf.nodes.MushroomKing_4.geometry}
            material={gltf.materials.Eye_White}
            skeleton={gltf.nodes.MushroomKing_4.skeleton}
          />
          <T.SkinnedMesh
            name="MushroomKing_5"
            geometry={gltf.nodes.MushroomKing_5.geometry}
            material={gltf.materials.Eye_Black}
            skeleton={gltf.nodes.MushroomKing_5.skeleton}
          />
        </T.Group>
        <T.Group name="Mushroom" position={[1.93, 1.76, -0.23]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <T.SkinnedMesh
            name="Mushroom_1"
            geometry={gltf.nodes.Mushroom_1.geometry}
            material={gltf.materials.MushroomKing_Main}
            skeleton={gltf.nodes.Mushroom_1.skeleton}
          />
          <T.SkinnedMesh
            name="Mushroom_2"
            geometry={gltf.nodes.Mushroom_2.geometry}
            material={gltf.materials.MushroomKing_Secondary}
            skeleton={gltf.nodes.Mushroom_2.skeleton}
          />
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
